name: first
on: 
  push:
    branches: 
      - main

jobs: 
  job1:
    name: First Job
    runs-on: ubuntu-latest
    steps: 
      - name: steps one
        uses: actions/checkout@v2
      - name: steps two
        run: env | sort

  job2:
    name: Second Job
    runs-on: windows-latest
    steps: 
      - name: steps one
        uses: actions/checkout@v2
      - name: steps two
        run: "Get-ChildItem Env: | Sort-Object Name"

  job3:
    name: Third Job
    runs-on: macos-latest
    steps: 
      - name: steps one
        uses: actions/checkout@v2
      - name: steps two
        run: env | sort
  job4:
    needs: [job1, job2, job3]
    name: Fourth job
    runs-on: macos-latest
    steps:
      - name: steps one
        uses: actions/checkout@v2
