name: marketplace
on: push

jobs:
  marketplace-job:
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Marketplace Job
        uses: cclauss/Find-Python-syntax-errors-action@v0.2.0    